// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKM1OpHDW2X4pizuzgn1wZJ_9V2kx8-IA',
    appId: '1:658648062009:web:a74df6122181d3083c55e8',
    messagingSenderId: '658648062009',
    projectId: 'chat-906a0',
    authDomain: 'chat-906a0.firebaseapp.com',
    storageBucket: 'chat-906a0.firebasestorage.app',
    measurementId: 'G-BV5KTPBW1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUC0RB7gDhmn8n307n8nqnjZS-DZtKP_8',
    appId: '1:658648062009:android:035bbf27842dfe223c55e8',
    messagingSenderId: '658648062009',
    projectId: 'chat-906a0',
    storageBucket: 'chat-906a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZQABQ0N-RMSo1V_OkJIYQL3GupwWwUQw',
    appId: '1:658648062009:ios:f2e36de15f25c8a93c55e8',
    messagingSenderId: '658648062009',
    projectId: 'chat-906a0',
    storageBucket: 'chat-906a0.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZQABQ0N-RMSo1V_OkJIYQL3GupwWwUQw',
    appId: '1:658648062009:ios:f2e36de15f25c8a93c55e8',
    messagingSenderId: '658648062009',
    projectId: 'chat-906a0',
    storageBucket: 'chat-906a0.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKM1OpHDW2X4pizuzgn1wZJ_9V2kx8-IA',
    appId: '1:658648062009:web:d5dc1006f906aff33c55e8',
    messagingSenderId: '658648062009',
    projectId: 'chat-906a0',
    authDomain: 'chat-906a0.firebaseapp.com',
    storageBucket: 'chat-906a0.firebasestorage.app',
    measurementId: 'G-8P6LRJ17ZF',
  );
}
